# Generated by Django 4.0.2 on 2022-02-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_income_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
    ]
