# Generated by Django 4.0.2 on 2022-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_income_options_remove_income_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
