# Generated by Django 4.0.2 on 2022-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_income_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='type_choice',
            field=models.CharField(choices=[('in', 'Income'), ('ex', 'Expense')], default='Income', max_length=2),
        ),
    ]
