# Generated by Django 4.0.2 on 2022-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_income_type_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type_choice',
            field=models.CharField(choices=[('in', 'Income'), ('ex', 'Expense')], default='in', max_length=2),
        ),
    ]
